// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmQ-YXjnjPRhkpCQesDEEDJXzx8ddlKc',
    appId: '1:312647624419:web:d383524436f52d7d5987d6',
    messagingSenderId: '312647624419',
    projectId: 'manicode-1016f',
    authDomain: 'manicode-1016f.firebaseapp.com',
    storageBucket: 'manicode-1016f.firebasestorage.app',
    measurementId: 'G-6V86N1ZZE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgxrWgNMYq_7Q9TkaQvjB9YJ9dVbg9hMA',
    appId: '1:312647624419:android:6c6dafcfa52499e45987d6',
    messagingSenderId: '312647624419',
    projectId: 'manicode-1016f',
    storageBucket: 'manicode-1016f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCzirPS0cK83d88GG5Dpov7PkEeB06Fw',
    appId: '1:312647624419:ios:ebad0c558b499a795987d6',
    messagingSenderId: '312647624419',
    projectId: 'manicode-1016f',
    storageBucket: 'manicode-1016f.firebasestorage.app',
    iosBundleId: 'com.example.manicode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNCzirPS0cK83d88GG5Dpov7PkEeB06Fw',
    appId: '1:312647624419:ios:ebad0c558b499a795987d6',
    messagingSenderId: '312647624419',
    projectId: 'manicode-1016f',
    storageBucket: 'manicode-1016f.firebasestorage.app',
    iosBundleId: 'com.example.manicode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQmQ-YXjnjPRhkpCQesDEEDJXzx8ddlKc',
    appId: '1:312647624419:web:1acc23af015917ce5987d6',
    messagingSenderId: '312647624419',
    projectId: 'manicode-1016f',
    authDomain: 'manicode-1016f.firebaseapp.com',
    storageBucket: 'manicode-1016f.firebasestorage.app',
    measurementId: 'G-9WZQNRNE0E',
  );
}
